language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - travis_retry composer self-update
  - travis_retry composer config --global github-oauth.github.com b7244dc99194b22416d5ce46d511ce04049b23de
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - echo 'mbstring.internal_encoding = "UTF-8"' >> ~/.phpenv/versions/5.4/etc/conf.d/travis.ini
  - echo 'mbstring.internal_encoding = "UTF-8"' >> ~/.phpenv/versions/5.5/etc/conf.d/travis.ini
  # js tests
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - npm install grunt grunt-contrib-qunit

script:
  - vendor/bin/codecept run --config tests/php/codeception.yml unit --coverage-xml
  - vendor/bin/coveralls
  - grunt qunit

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

# faster builds on new travis setup not using sudo
sudo: false