language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - travis_retry composer self-update
  - travis_retry composer config --global github-oauth.github.com b7244dc99194b22416d5ce46d511ce04049b23de
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  - echo 'mbstring.internal_encoding = "UTF-8"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # prepare JS
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - npm install
  - npm run build

script:
  - vendor/bin/codecept run --config tests/php/codeception.yml unit --coverage-xml
  - vendor/bin/coveralls
  - npm run test

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

# faster builds on new travis setup not using sudo
sudo: false